name: atlas_app
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 0.0.5+8

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  encrypt: ^5.0.3
  crypto: ^3.0.6
  flutter_svg: ^2.0.17
  package_info_plus: ^8.3.0
  flutter_langdetect: ^0.0.2
  translator: ^1.0.3+1
  retry: ^3.1.2
  badges: ^3.1.2
  easy_image_viewer: ^1.5.1
  animate_do: ^4.2.0
  url_launcher: ^6.3.1
  image_cropper: ^9.0.0
  image_picker: ^1.1.2
  restart_app: ^1.3.2
  flutter_local_notifications: ^19.1.0
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  loading_animation_widget: ^1.3.0
  flutter_image_compress: ^2.4.0
  flutter_dotenv: ^5.2.1
  flutter_lucide: ^1.6.2
  hexcolor: ^3.0.1
  toastification: ^3.0.2
  go_router: ^14.8.1
  flutter_riverpod: ^2.6.1
  rxdart: ^0.28.0
  supabase_flutter: ^2.8.4
  dio: ^5.8.0+1
  flutter_avif: ^3.0.0
  pinput: ^5.0.1
  image: ^4.5.4
  ffi: ^2.1.4
  path_provider: ^2.1.5
  path: ^1.9.1
  uuid: ^4.5.1
  shared_preferences: ^2.5.3
  flutter_datetime_picker_plus: ^2.2.0
  intl: ^0.19.0
  firebase_storage: ^12.4.5
  convert: ^3.1.2
  flutter_tabler_icons: ^1.43.0
  fancy_shimmer_image: ^2.0.3
  collection: ^1.19.1
  flutter_rating_bar: ^4.0.1
  msh_checkbox: ^2.0.1
  firebase_core: ^3.13.0
  loader_overlay: ^5.0.0
  flutter_carousel_widget: ^3.1.0
  gallery_image_viewer: ^1.2.0
  gal: ^2.3.1
  mime: ^2.0.0
  like_button: ^2.0.5
  mime_type: ^1.0.1
  flutter_portal: ^0.4.0
  comment_tree: ^0.3.0
  timeago: ^3.7.0
  petitparser: ^6.1.0
  async: ^2.12.0
  app_links: ^6.4.0
  clipboard: ^0.1.3
  flutter_quill: ^11.2.0
  social_sharing_plus: ^1.2.3
  screenshot: ^3.0.0
  no_screenshot: ^0.3.1
  popup_menu_plus: ^0.0.6
  share_plus: ^10.1.4
  firebase_messaging: ^15.2.5
  firebase_analytics: ^11.4.5
  firebase_remote_config: ^5.4.3
  permission_handler: ^12.0.0+1
  open_file: ^3.5.10
  flutter_downloader: ^1.12.0
  app_installer: ^1.3.1
  flutter_hooks: ^0.21.2
  hooks_riverpod: ^2.6.1
  firebase_crashlytics: ^4.3.5
  visibility_detector: ^0.4.0+2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/images/
    - .env
    - shorebird.yaml

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: BebasNeue
      fonts:
        - asset: assets/fonts/BebasNeue-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
    - family: Manrope
      fonts:
        - asset: assets/fonts/Manrope-VariableFont_wght.ttf

    - family: Urbanist
      fonts:
        - asset: assets/fonts/Urbanist-VariableFont_wght.ttf

    - family: Lateef
      fonts:
        - asset: assets/fonts/Lateef-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Lateef-Light.ttf
          weight: 300
        - asset: assets/fonts/Lateef-Regular.ttf
          weight: 400
        - asset: assets/fonts/Lateef-Medium.ttf
          weight: 500
        - asset: assets/fonts/Lateef-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Lateef-Bold.ttf
          weight: 700
        - asset: assets/fonts/Lateef-ExtraBold.ttf
          weight: 800

    - family: Zain
      fonts:
        - asset: assets/fonts/Zain-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/Zain-Light.ttf
          weight: 300
        - asset: assets/fonts/Zain-Regular.ttf
          weight: 400
        - asset: assets/fonts/Zain-Bold.ttf
          weight: 700
        - asset: assets/fonts/Zain-Black.ttf
          weight: 900
        - asset: assets/fonts/Zain-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Zain-Italic.ttf
          style: italic
          weight: 400
        - asset: assets/fonts/Zain-LightItalic.ttf
          style: italic
          weight: 300

    - family: Vazirmatn
      fonts:
        - asset: assets/fonts/Vazirmatn-VariableFont_wght.ttf


  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
